# config.py

# --- AGGRESSIVE EXPERIMENTAL MODE ---
SYMBOL = "SOLUSDT"
TIMEFRAME = "5m"
DATA_LIMIT = 1500

# --- RISK MANAGEMENT ---
INITIAL_BALANCE = 10000.0
ACCOUNT_RISK_PER_TRADE = 0.03
MAX_LEVERAGE = 30

# --- REALISTIC EXECUTION SIMULATION ---
TAKER_FEE = 0.0004
SLIPPAGE_PCT = 0.0010

# --- RUBBER BAND ANOMALY PARAMS ---
BB_PERIOD = 20
BB_STD = 3.0

RSI_PERIOD = 7
RSI_OB = 85
RSI_OS = 15

ATR_PERIOD = 14

ATR_SL_MULTIPLIER = 4.0
ATR_TP_MULTIPLIER = 1.0